[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python manage.py migrate && daphne -b 0.0.0.0 -p $PORT private_chat_app.asgi:application"